### ISSUE TITLE
Switch to aws-sdk-v3 in Serverless Template

### ISSUE THREAD

**Issue by samchungy** [seek-oss/skuba#1019]
Node 18 image will come with aws-sdk-v3. So we should switch out the pre-hooks for v3 counterparts. 

https://github.com/aws/aws-lambda-base-images/issues/47#issuecomment-1292011841

**Comment by 72636c** [comment]
@samchungy have you had good luck with excluding local dependencies, i.e. listing them under dev dependencies, having Serverless prune them during deployment, and relying on the preinstalled SDK?

**Comment by samchungy** [comment]
> @samchungy have you had good luck with excluding local dependencies, i.e. listing them under dev dependencies, having Serverless prune them during deployment, and relying on the preinstalled SDK?

Haven't actually tried that yet with v3 since it isn't included in the current runtime yet ^

**Comment by 72636c** [comment]
🤦 of course
