### ISSUE TITLE
Autofixes on Renovate Branches

### ISSUE THREAD

**Issue by samchungy** [seek-oss/skuba#1070]
![image](https://user-images.githubusercontent.com/18017094/208789409-b7328238-d69a-4a0d-8a67-5b83834fcdfd.png)

Skuba runs autofixes on Renovate branches before the PR is created sometimes meaning we have to create them manually.

**Comment by 72636c** [comment]
Can this occur even with [prCreation: 'immediate'](https://docs.renovatebot.com/configuration-options/#prcreation)?

I'm not sure if we have a general way of solving this outside of defining a separate pipeline to run on PRs rather than branches.

**Comment by samchungy** [comment]
Ooo haven't tried that. Still oin the default preset for most of my repos

**Comment by 72636c** [comment]
Ah, if you're on the default then it should already be in place and isn't a silver bullet then: https://github.com/seek-oss/rynovate/blob/c93abf7c48a757e484fd345c2b06dd2dc0d6eac1/default.json#L140-L143
