### ISSUE TITLE
lint: Create migration path to `FlatESLint`

### ISSUE THREAD

**Issue by 72636c** [seek-oss/skuba#1157]
https://eslint.org/docs/latest/use/configure/configuration-files-new

eslint/eslint#13481

---

This may be a two-step process:

1. Release (auto-fixable?) version that will upgrade projects to flat config
2. Release subsequent major version for ESLint 9 where old config format is removed

**Comment by samchungy** [comment]
https://github.com/seek-oss/eslint-config-seek/pull/136

Typescript Eslint added support in 7.2.0. Pending seek config changes we should look to migrate by creating a patch
