### ISSUE TITLE
Skuba uses yarn to install dependencies after running skuba configure instead of the current package manager

### ISSUE THREAD

**Issue by ConradLang** [seek-oss/skuba#1246]
## Problem

When `skuba configure` updates dependencies, it runs `yarn install` instead of using the repo's package manager.

## Background

Skuba was developed when `yarn` was the default package manager.  
Some teams are moving to `pnpm` instead.

It would be nice if the default package manager could be specified e.g. in the `skuba` section of the `package.json` where the default `yarn` could be overridden by another supported package manager e.g. `pnpm`.

An example of this issue is:

```text
~/projects/team/some-api > renovate-skuba-7.x > pnpm skuba configure

    ╭─╮     ╭─╮
╭───│ ╰─╭─┬─╮ ╰─╮───╮
│_ ─┤  <│ ╵ │ • │ • │
╰───╰─┴─╰───╯───╯── ╰

7.1.1 | latest 7.1.1

Detected project root: /Users/username/projects/team/some-api

Dependencies:

✔ No changes

Dev dependencies:

D @types/jest ^29.5.2
D jest ^29.5.0
D tsconfig-seek ^2.0.0

✔ Apply changes? · yes

Config:

M package.json
M tsconfig.json

✔ Apply changes? · yes

yarn install v1.22.19
$ npx only-allow pnpm
npm WARN exec The following package was not found and will be installed: only-allow@1.1.1
╔═════════════════════════════════════════════════════════════╗
║                                                             ║
║   Use "pnpm install" for installation in this project.      ║
║                                                             ║
║   If you don't have pnpm, install it via "npm i -g pnpm".   ║
║   For more details, go to https://pnpm.js.org/              ║
║                                                             ║
╚═════════════════════════════════════════════════════════════╝
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

✗ Failed to install dependencies. Resume with:

yarn install
yarn format
```

- Note that there is a `preinstall` script in `package.json` that only allows `pnpm`:

  ```json
     "preinstall": "npx only-allow pnpm",
  ```

## References

Some examples where `yarn` is used are:

- https://github.com/seek-oss/skuba/blob/90b18e0a38b0770116706ac4ef30b56aaa0f2224/src/cli/configure/index.ts#L111
- https://github.com/seek-oss/skuba/blob/90b18e0a38b0770116706ac4ef30b56aaa0f2224/src/cli/init/index.ts#L88

**Comment by 72636c** [comment]
N.B. this also highlights an issue with `configure` where it is overzealous in removing dependencies that skuba already includes:

```
D @types/jest ^29.5.2
D jest ^29.5.0
D tsconfig-seek ^2.0.0
```

Unfortunately pnpm does not work well with this model. At minimum we need to remove this logic, but ideally we would find a happier medium where pnpm does not require such internals to be exposed to the project.

**Comment by AaronMoat** [comment]
With regards to:

> where pnpm does not require such internals to be exposed to the project

Would it work if skuba managed a section of pnpm-workspace.yaml with lines like `public-hoist-pattern[]=@types/jest` (for pnpm)? I think that would mean it's not required in the package.json, similar to yarn installs.

**Comment by samchungy** [comment]
Does it support adding the patterns to a pnpm file? Last we checked you had to add it to a npmrc file @AaronMoat

**Comment by 72636c** [comment]
Maybe we need to manage `.npmrc` then; with the proliferation of pnpm I think we need to commit that file anyway and have its containing configuration respected in CI. The problem with our current templated Dockerfiles is that we mount the token-laden secret at the project-level `/workdir/.npmrc`; we can try mounting at the user-level `~/.npmrc` instead to avoid conflicts.

**Comment by AaronMoat** [comment]
@samchungy yes you're right. I misread https://pnpm.io/npmrc (it mentions pnpm-workspace.yaml just for a directory location). 

Starting to manage npmrc probably makes a lot of sense. Just need to be very careful with backwards compatibility on exposing secrets by accident, and potentially people having it in their gitignore manually or other special handling that exists outside of skuba might get fiddly.

**Comment by samchungy** [comment]
Yep, that was our concern when it came to .npmrc

**Comment by 72636c** [comment]
I think #1289 resolves this
