### ISSUE TITLE
pnpm migration

### ISSUE THREAD

**Issue by samchungy** [seek-oss/skuba#1285]
Thread to keep track of all pnpm related threads

Lint Hanging: https://github.com/seek-oss/skuba/issues/836
Configure uses yarn: https://github.com/seek-oss/skuba/issues/1246
Manage .npmrc: https://github.com/seek-oss/skuba/issues/1286
Serverless support: https://github.com/seek-oss/skuba/issues/1287

**Comment by 72636c** [comment]
Closing this one as the remaining work is pinned and tracked under #1286
