### ISSUE TITLE
Manage .npmrc

### ISSUE THREAD

**Issue by samchungy** [seek-oss/skuba#1286]
We need to manage the repository .npmrc file in order to be able to hoist some of skuba's internal dependencies.

```
# managed by skuba
public-hoist-pattern[]="*eslint*"
public-hoist-pattern[]="*prettier*"
public-hoist-pattern[]="@types*"
public-hoist-pattern[]="*jest*"
public-hoist-pattern[]="tsconfig-seek"
# end managed by skuba
```

This presents a couple of issues, so in our upgrade script we need:

1. We need to modify the .dockerIgnore file, .gitIgnore file to no longer ignore .npmrc. We could potentially do this based on the existence of a pnpm lock file

2. If a workspace has an existing .npmrc file with an auth token we should discard it and place our .npmrc in its place. If it has existing settings we can place it below our managed section.

**Comment by 72636c** [comment]
I think the last thing to cover off for the [next version](https://github.com/seek-oss/skuba/pull/1329#issuecomment-1859528370) is to ensure

> Ignore file refreshing and skuba configure do not expose or otherwise mangle existing private .npmrcs

We should review if this comment is still relevant:

https://github.com/seek-oss/skuba/blob/47653f749e0bde9f5539cba3d83cb43d6dc5f4d9/src/cli/lint/internalLints/refreshIgnoreFiles.ts#L25-L29
