### ISSUE TITLE
Build Fails When the Buildkite Annotation is Too Long

### ISSUE THREAD

**Issue by ConradLang** [seek-oss/skuba#1331]
The maximum body size of a Buildkite annotation is `1 MiB` as per [Buildkite - Creating an annotation](https://buildkite.com/docs/agent/v3/cli-annotate#creating-an-annotation).

When the body size is greater than `1 MiB`, an error occurs (e.g. [backoffice-access Build 1727 Line 2604](https://buildkite.com/seek/backoffice-access-pr/builds/1727#018c2223-575b-4549-bbc7-5ef1cc512250/402-2640))

```text
Error: Command failed with E2BIG: buildkite-agent annotate --context build-associations.association-diff --style warning ...
```

The [Buildkite.annotate](src/api/buildkite/annotate.ts) function could possibly truncate the annotation similar to [buildkite-plugins/junit-annotate-buildkite-plugin L28-L32](https://github.com/buildkite-plugins/junit-annotate-buildkite-plugin/blob/master/hooks/command#L28-L32) (as suggested by @72636c in [Slack](https://seekchat.slack.com/archives/C02NTMZMRQF/p1701916328999139?thread_ts=1701380175.561809&cid=C02NTMZMRQF)) although that may break the annotation anyway or result in an inaccurate annotation.

**Comment by GeordieEK** [comment]
Would it be feasible to split offending annotation bodies into multiple annotations?
I'm not too familiar with buildkite nor do I have access to that particular error, but maybe something like this? 

```ts
const MAX_SIZE_IN_BYTES = 1024 * 1024; // 1 MiB

export const annotate = async (
  markdown: string,
  opts: AnnotationOptions = {},
): Promise<void> => {
  if (!(await isAnnotationEnabled())) {
    return;
  }

  // Always scope to the current Buildkite step.
  const context = [
    opts.scopeContextToStep && process.env.BUILDKITE_STEP_ID,
    opts.context,
  ]
    .filter(Boolean)
    .join('|');

  const { style } = opts;

  // If markdown content exceeds the max size, chunk it
  const contentSizeInBytes = Buffer.byteLength(markdown, 'utf8');
  if (contentSizeInBytes > MAX_SIZE_IN_BYTES) {
    const chunks = splitMarkdownIntoChunks(markdown, MAX_SIZE_IN_BYTES);
    for (let i = 0; i < chunks.length; i++) {
      const chunkContext = `${context}-part${i + 1}`;
      await exec(
        'buildkite-agent',
        'annotate',
        ...(chunkContext ? ['--context', chunkContext] : []),
        ...(style ? ['--style', style] : []),
        chunks[i] ?? '',
      );
    }
  } else {
    // If the content is within the size limit, create a single annotation
    await exec(
      'buildkite-agent',
      'annotate',
      ...(context ? ['--context', context] : []),
      ...(style ? ['--style', style] : []),
      markdown,
    );
  }
};

export const splitMarkdownIntoChunks = (
  markdown: string,
  maxSizeInBytes: number,
): string[] => {
  const chunks: string[] = [];
  let currentChunk = '';
  const markdownLines = markdown.split('\n');

  for (const line of markdownLines) {
    // Chunk line if it exceeds the maximum size
    if (
      Buffer.byteLength(`${currentChunk}${line}\n`, 'utf8') > maxSizeInBytes
    ) {
      chunks.push(currentChunk.trim());
      currentChunk = '';
    }

    currentChunk += `${line}\n`;

    // Chunk if the line is the end of a paragraph or a section
    if (line.match(/^\s*$/)) {
      chunks.push(currentChunk.trim());
      currentChunk = '';
    }
  }

  // Add last chunk if it's not empty
  if (currentChunk.trim() !== '') {
    chunks.push(currentChunk.trim());
  }

  return chunks;
};
```

**Comment by ConradLang** [comment]
Splitting the annotation bodies into multiple annotations is an option but you'd then need to consider deleting the annotations when you re-run the step and need to delete / update the annotations.

While it should not be complicated to find and delete the related annotations (assuming there's a naming convention), it would be simpler to truncate the annotation but write the full message to the build log such that the information is still available even if not in the annotation.

**Comment by GeordieEK** [comment]
The annotation truncation seems to be working, I've included a warning as well. 

What's the best way to write to the build log? Thanks

```ts
  // Check if the annotation exceeds the maximum size
  const buffer = Buffer.from(markdown, 'utf-8');
  let truncatedMarkdown = markdown;
  if (buffer.length > MAX_SIZE) {
    // Notify user of truncation, leave space for message
    truncatedMarkdown =
      buffer.toString('utf-8', 0, MAX_SIZE - TRUNCATION_MESSAGE_LENGTH) +
      TRUNCATION_MESSAGE;
    // TODO: Log the full annotation to the build log
  }
```
