### ISSUE TITLE
Broken links in readme

### ISSUE THREAD

**Issue by maraisr** [seek-oss/skuba#14]
The links in the table below https://github.com/seek-oss/skuba#one-library-to-rule-them-all are broken.

---

Also; what is Gantry? Never heard of this before.

**Comment by maraisr** [comment]
Wait.. they're private repo things.

Hope one day i'll get to know these things :/

**Comment by 72636c** [comment]
Hey, sorry about that! There's a fair bit to do with the repo still and the README could definitely be clearer to newcomers.

It would be nice to make all the things OSS, but we gotta start somewhere 🙂
