### ISSUE TITLE
Tagging for `seek:env:prod` needs to be updated

### ISSUE THREAD

**Issue by lesterdongatseek** [seek-oss/skuba#1478]
### The issue

The template applies the tag `seek:env:production` where it should actually be `seek:env:prod`. Fairly trivial to update, will create a change for this.

**Comment by 72636c** [comment]
https://github.com/seek-oss/skuba/releases/tag/v7.5.1

**Comment by lesterdongatseek** [comment]
ah cool that's pretty new

**Comment by lesterdongatseek** [comment]
there's a bit in the readme to update, still has `seek:env:production` in the readme

**Comment by 72636c** [comment]
Ah, do you have a link to where that reference is @lesterdongatseek? (You're welcome to PR of course 🙂)
