### ISSUE TITLE
Renovate + changesets investigation

### ISSUE THREAD

**Issue by AaronMoat** [seek-oss/skuba#1493]
Look into: 

- Auto generating changesets for renovates in the skuba repository, so we can't forget to generate one 
- Using `gitIgnoredAuthors` for the above to not lock the PRs after first commit.
- Extending `gitIgnoredAuthors` for the general SEEK ecosystem in combination with skuba autofixes, to not lock renovate PRs after first commit

**Comment by AaronMoat** [comment]
We can try again when v38 is released: https://github.com/renovatebot/renovate/issues/27992

**Comment by samchungy** [comment]
Can we delete https://github.com/seek-oss/skuba/blob/3310e6ed714cd4b06b03890c5c900e33b20b9ab9/src/cli/lint/autofix.ts#L74 if it lands?

**Comment by AaronMoat** [comment]
Ah nice. Yes, likely, though it means that we're relying on users using rynovate* for it to work nicely. Which, maybe is ok

(*unless this makes momentum: https://github.com/seek-oss/renovate-config-seek/pull/21)
