### ISSUE TITLE
Bun support

### ISSUE THREAD

**Issue by farhan-helmy** [seek-oss/skuba#1628]
Is there already experiment for SKUBA to support Bun and Typescript out of the box?

**Comment by AaronMoat** [comment]
Hey @farhan-helmy, 

Short answer: no 

Longer answer: 

- Skuba bundles a `skuba node` command where you can run typescript files directly 
- If you'd like to run Typescript directly in production without a build step, that's not currently supported, and unlikely to be in the near future without a compelling argument (unless you can make one!) 

If you'd like to discuss this further, I can expand on this & recommend reaching out in our private slack in our skuba support channel :)
