### ISSUE TITLE
lambda-sqs-worker-cdk: use aws-codedeploy-hooks

### ISSUE THREAD

**Issue by AaronMoat** [seek-oss/skuba#1640]
Would be good to avoid copy-paste (via template) with https://github.com/seek-oss/aws-codedeploy-hooks.

**Comment by aurelius0523** [comment]
@AaronMoat, I was trying to take a crack at this to learn more about `skuba` but am confused about the [pre and post hook](https://github.com/seek-oss/aws-codedeploy-hooks/blob/39bbb7dfcfc97e1b0acf1786caa59ef17ac90379/packages/infra/src/constructs/lambdaDeployment.ts#L49) required by `LambdaDeployment` construct. 

### Question 1
Why does the construct listen to two lambdas (`aws-codedeploy-hook-BeforeAllowTraffic` and `aws-codedeploy-hook-AfterAllowTraffic`)  that are account-wide? Should it not allow the construct user to pass in their own `pre` and `post` hook lambda with their own logic? Something along this line: 

```ts
 const workerDeployment = new LambdaDeployment(this, 'workerDeployment', {
      lambdaFunction: worker,
      preHook: new aws_lambda.Function(this, 'preHookWorker', {
        architecture: aws_lambda.Architecture[architecture],
        code: new aws_lambda.AssetCode('./lib'),
        runtime: aws_lambda.Runtime.NODEJS_18_X,
        handler: 'preHook.handler',
        functionName: 'aws-codedeploy-hook-AfterAllowTraffic',
      }),
      postHook: new aws_lambda.Function(this, 'postHookWorker', {
        architecture: aws_lambda.Architecture[architecture],
        code: new aws_lambda.AssetCode('./lib'),
        runtime: aws_lambda.Runtime.NODEJS_18_X,
        handler: 'postHook.handler',
        functionName: 'aws-codedeploy-hook-AfterAllowTraffic',
      }),
    });
```

### Question 2
I see that the two hooks are created [here](https://github.com/seek-oss/aws-codedeploy-hooks/blob/39bbb7dfcfc97e1b0acf1786caa59ef17ac90379/packages/infra/src/constructs/stack.ts#L51). I also noticed that the pre and post lambda uses [the same index.handler here](https://github.com/seek-oss/aws-codedeploy-hooks/blob/39bbb7dfcfc97e1b0acf1786caa59ef17ac90379/packages/infra/src/constructs/lambda.ts#L23). Is there some ways for user to specify different logic for `pre` and `post` hook that I am missing?

**Comment by AaronMoat** [comment]
Hi @aurelius0523! Happy to iterate on the design of aws-codedeploy-hooks, but there are some simplicity benefits to the deploy-once strategy. I could see a world where both are supported? cc @72636c 

Inside the functions, it’s internally forking to different codepaths. We could point to seperate files as well, I think this was just convenience.

**Comment by aurelius0523** [comment]
I have created a [PR](https://github.com/seek-oss/skuba/pull/1644) to move to `aws-codedeploy-hooks` as is. Happy to discuss further. No rush, I am just trying to explore libraries at seek 😄

**Comment by 72636c** [comment]
Apologies for the late revert @AaronMoat @aurelius0523! How I was thinking this would work in practice is as follows:

1. Team looks to deploy their first Lambda function with the CDK
2. They deploy it in a seemingly self-contained manner, i.e. they would include both `HookStack` and `LambdaDeployment` in the CDK app
3. Team looks to deploy their second Lambda function with the CDK
4. They can now move `HookStack` to its own CDK app given it will be shared across the two functions

While I'm not fully convinced yet, I can definitely see some upside in providing the _option_ for teams to continue to keep things separate in Step 4 🙂
