### ISSUE TITLE
Pasting a team/repository name into skuba init results in garbage on the screen

### ISSUE THREAD

**Issue by koterpillar** [seek-oss/skuba#229]
To reproduce:

* `npx skuba init`
* Navigate to the `<repo>` placeholder
* In another window, copy "completely-fake-repo" to clipboard
* Paste into the terminal

Expected result:

* Repository name is filled in

Actual result:

<img width="1915" alt="Screenshot" src="https://user-images.githubusercontent.com/140276/95697249-cdef5880-0c89-11eb-860a-be360b280236.png">

**Comment by 72636c** [comment]
This appears to be an upstream bug with [Enquirer](https://github.com/enquirer/enquirer#snippet-prompt):

```javascript
const { Snippet } = require('enquirer');

const prompt = new Snippet({
  name: 'snippet',
  message: 'Enter:',
  fields: [{ name: 'id', message: 'ID' }],
  template: '{\n  "id": "${id}"\n}',
});

prompt.run();
```

It might be worth revising this initial prompt, given the snippet is generally awkward to use
