### ISSUE TITLE
koa-cluster boilerplate code

### ISSUE THREAD

**Issue by runk** [seek-oss/skuba#352]
Assigning the port to the `app` is a way to make `koa-cluster` working, however not required for the normal `app.listen` as it's currently done in the template. 

https://github.com/seek-oss/skuba/blob/master/template/koa-rest-api/src/app.ts#L9-L11: 
```
export default Object.assign(app, {
  port: config.port,
});
```

Just pointing it out that can be converted to 

```
export default app;
```

given that first snippet doesn't work for koa-cluster without changes anyway (i.e. doing `exports = thing`)

**Comment by 72636c** [comment]
FWIW `port` is also interpreted by `skuba start` in lieu of an explicit `--port` option.

**Comment by runk** [comment]
I didn't spent too much time digging but looks like https://github.com/seek-oss/skuba/blob/master/src/cli/start.ts#L27 attempts to use params like `--port=1234` ?
