### ISSUE TITLE
Support independent fixup scripts

### ISSUE THREAD

**Issue by 72636c** [seek-oss/skuba#409]
As best practices evolve, it's easy for existing repos to fall behind. Having a command that allows you to browse suggestions or automatic fixers would make upkeep a simpler process. These shouldn't require much buy-in to the base skuba templates either as we know that teams will deviate.

A reasonable starting point would be the existing monolithic `skuba configure` command. Breaking that command up into multiple separate submodules that would make initial configuration a lot less hamfisted while also enabling this exact use case.

Examples of potential fixups include:

1. Upgrading to the latest Node.js version
1. Adopting `serverless-plugin-canary-deployments`

There's also opportunity to roll glaring issues into custom linting rules that are packaged up into `skuba lint`. That would give us the power to break CI if the issue is deemed serious enough.

**Comment by samchungy** [comment]
I believe https://github.com/seek-oss/skuba/pull/1382 resolved this
