### ISSUE TITLE
Discussion: What do you guys think about this?

### ISSUE THREAD

**Issue by ak-08** [seek-oss/skuba#432]
While hacking a `Skuba-ish` package at REA, one of my colleagues showed me [Projen](https://github.com/projen/projen).

This has off-the-bat TypeScript scaffolds but also lets you define your own custom ones. The only thing that annoys me is this but I could live with it: 

> As opposed to existing templating/scaffolding tools, projen is not a one-off generator. Synthesized files should never be manually edited (in fact, projen enforces that). To modify your project setup, users interact with rich strongly-typed class and execute projen to update their project configuration files.

**Comment by 72636c** [comment]
Hey stranger! Didn't mean to ignore this 😅.

I think that looks pretty cool and seems a bit more along the lines of how sku handles its synthesised files. In theory something like skuba could wire itself up to use Projen under the hood if it's got a lot of upside.

A few points I'd note here:

1. skuba started out very conservatively with the goal in mind that we could always drop individual features or even the whole package if we didn't get much adoption and/or found that core TypeScript tooling or an alternative toolkit was mature enough to adopt instead. To that end it was written as a collection of extendable configs that could be decoupled (for example, you can use `eslint-config-skuba` by itself). The Projen/sku approach is definitely more maintainable and I'd probably lean more in that direction if we were to start over with a guarantee that we'd make it into SEEK's technology strategy.
2. I just skimmed Projen so I'm not sure of the extent of its customisability, but you'll always have a bit more control if you're working off of a fork or maybe even your own superset wrapper. If that matters to you.
2. There are a few ecosystem concerns (e.g. Yarn Berry, Babel vs tsc, ESM) where you may want to have control over whether/when support should land.
