### ISSUE TITLE
Skuba Configure Renaming Issue

### ISSUE THREAD

**Issue by samchungy** [seek-oss/skuba#582]
Not a big issue but when I ran `skuba configure` to update an API, it renamed `dist` to `lib`, the rename might want to use exact matching:

![image](https://user-images.githubusercontent.com/18017094/135368912-af312c88-324f-4237-b7da-e2a065c03240.png)

It changed `distroless` to `libroless` 😄

**Comment by 72636c** [comment]
Thanks for raising, `skuba configure` is pretty undercooked at the moment. I hope to make it less aggressive and more modular in a future (next?) release.
