### ISSUE TITLE
Investigate esbuild for `skuba build`

### ISSUE THREAD

**Issue by 72636c** [seek-oss/skuba#588]
This presents a few opportunities while still preserving partial compatibility with our existing `tsconfig.json`-based builds with `tsc`:

- Bundle code to improve cold start time, particularly in AWS Lambda
- Extend the build process with plugins, including build-time module alias resolution
- In-process execution, as it supports a convenient Node.js API while `tsc` is CLI-only
- Faster builds, as it skips type checking which we already handle on lint

**Comment by samchungy** [comment]
Another thing to note is that it has treeshaking enabled by default with no option to turn it off which gives us huge benefits with lambda packaging sizes.

However, you will have to expose the `external` esbuild option to be able to package some libraries with optional peer dependencies without needing to declare those optional deps as dependencies.
