### ISSUE TITLE
Unexpected mutation when calling `Jest.mergePreset`

### ISSUE THREAD

**Issue by jahredhope** [seek-oss/skuba#593]
When implementing https://github.com/seek-oss/skuba/pull/592 I noticed that Jest.mergePreset both mutates the internal jest-preset and returns the result.

When using the function I hadn't expected it to mutate the default preset.

This likely doesn't affect consumers as I can't think of any reason you'd call mergePreset (and therefore access the jest-preset) multiple times, however it's noticeable when running Jest tests for skuba, where the [current tests](https://github.com/seek-oss/skuba/blob/9146b4a26b2d8270179ad6e4221d469d365d4c3e/src/api/jest/index.test.ts) fail if ran in isolation as they expect the mutations from the previous tests.

I don't think having `Jest.mergePreset` both return the result and mutate the underlying default is intuitive and could cause a bug in the future.

Perhaps rather than introducing a breaking change it would be worth creating `Jest.withDefault` that does the same thing without mutation and deprecating the old?

Or if "mutate and return" is ideal perhaps it would be worth making the current description even more clear (it already does say this, but it doesn't say `mutate` so I didn't realise).

I'd be happy to PR either of these if they are a good idea, but also realise this is just an opinion so happy to just close the issue if prefered.

**Comment by 72636c** [comment]
This looks like unintended behaviour so I think we can fix it without requiring a major version bump. If I understand correctly, we should be using `mergeWith({}, obj, src, ...)` rather than `mergeWith(obj, src, ...)`?

**Comment by jahredhope** [comment]
So just wanted to check whether we can make the change in record.ts itself. It's safer than I thought:

`mergeRaw` is only used for this Jest work

`merge` is used in two places,
- one of which has a slight risk to change but I think whats happening now is dangerous.
   src/cli/configure/modules/package.ts
- The other is safe to change as the object is created in the method and not reused.
   src/cli/configure/modules/tsconfig.ts


So happy to PR that.
