### ISSUE TITLE
GitHub Annotations for test

### ISSUE THREAD

**Issue by samchungy** [seek-oss/skuba#638]
Add [GitHub Annotations](https://github.com/seek-oss/skuba/issues/619) for `skuba test`.

### Users may have multiple tests (unit/integration) they run with Jest, How do we decide what `name` to use for the Check Run - `skuba/${name}` eg. `skuba/test`

- Use Jest Projects display name
- Environment variable
- CLI flag?
- Pass an options argument to a [reporter](https://jestjs.io/docs/configuration#reporters-arraymodulename--modulename-options)
```
{
  "reporters": [
    "default",
    ["<rootDir>/my-custom-reporter.js", {"banana": "yes", "pineapple": "no"}]
  ]
}
```

### How do we implement annotations?

- Regex on Jest output
- Implement a Jest Reporter
  - Separate repo or js file reporter

**Comment by samchungy** [comment]
Looking into this - I think the best way to achieve this is to ask users to use the [displayName](https://jestjs.io/docs/configuration#displayname-string-object) field which is available in jest config files.

We could by default generate the name `skuba/test`.

eg.
`skuba/test - Build #50 passed (0 annotations added)`

and if they provide a `displayName` add it in brackets

eg. displayName: integration
`skuba/test (integration) - Build #50 passed (0 annotations added)`

However, this may not work for users who use a single `jest.config` file and instead augment the files to test with a script eg. skuba test --testMatch **.int.test.ts

but I think this would encourage users to create separate config files for different test types which I think is a better solution overall.

**Comment by 72636c** [comment]
`displayName` sounds good as long as we provide a sensible default; many projects will just have the one config and that's perfectly fine. It's also supported and recommended for multi-project configurations: https://jestjs.io/docs/configuration#projects-arraystring--projectconfig
