### ISSUE TITLE
Prettier Warning/Errors

### ISSUE THREAD

**Issue by samchungy** [seek-oss/skuba#659]
https://buildkite.com/seek/hirer-contracts-api/builds/1972#

Recently bumped up an API to Skuba 3.15.2. We got this error when running `yarn lint`.
![image](https://user-images.githubusercontent.com/18017094/141042058-1eacd66f-d29e-4377-9491-4685b94bbfe9.png)

Re-running it again worked however we get left with some warnings:

```
(node:30) Warning: File descriptor 32 closed but not opened in unmanaged mode
--
  | (Use `node --trace-warnings ...` to show where the warning was created)
  | Prettier │ Processed 85 files in 10.27s.

```

Ran --trace-warnings on local and got the following:

```
➜ node --trace-warnings node_modules/.bin/skuba lint                                                                                                                                           
(node:33523) Warning: File descriptor 43 closed but not opened in unmanaged mode
    at Object.closeSync (node:fs:530:11)
    at Object.closeSync (/Users/schung/repos/hirer-contracts-api/node_modules/graceful-fs/graceful-fs.js:74:20)
    at getInterpreter (/Users/schung/repos/hirer-contracts-api/node_modules/prettier/index.js:12674:30)
    at Object.inferParser (/Users/schung/repos/hirer-contracts-api/node_modules/prettier/index.js:12691:25)
    at getFileParser (/Users/schung/repos/hirer-contracts-api/node_modules/prettier/index.js:25444:36)
    at _getFileInfo (/Users/schung/repos/hirer-contracts-api/node_modules/prettier/index.js:25484:29)
    at getFileInfo (/Users/schung/repos/hirer-contracts-api/node_modules/prettier/index.js:25407:10)
    at async Promise.all (index 2)
```

**Comment by 72636c** [comment]
Ooh, that's a very useful stack trace. Looks like something is going wrong here: https://github.com/seek-oss/skuba/blob/v3.15.2/src/cli/adapter/prettier.ts#L126-L127

Is it possible to pinpoint whether a particular file is causing the issue with `yarn lint --debug`?

**Comment by samchungy** [comment]
![image](https://user-images.githubusercontent.com/18017094/141044251-8615df9a-6b25-4c6a-9185-0dae432ee359.png)
Comes from this file in Prettier 🤔 

![image](https://user-images.githubusercontent.com/18017094/141044147-81964037-34e7-48f4-9e1f-8f9023d18890.png)

Not sure if it's any particular file, when I deleted buildkite.yml it would show up on another file so it may just be an asynchronous warning.

**Comment by etaoins** [comment]
On `indie-graphql-server` this gets triggered by `.github/CODEOWNERS` and no other file. I’m not sure if this is related to the `EBADF`s that occasionally break its build.

**Comment by 72636c** [comment]
^ is pretty bizarre. The `indie-graphql-server` warning is indeed triggered exclusively on `.github/CODEOWNERS`, and only when running the relevant Prettier/`graceful-fs` code in a worker thread.
