### ISSUE TITLE
progress key wrongly set in cdk.json

### ISSUE THREAD

**Issue by bosonseek** [seek-oss/skuba#796]
Issue:

in the `lambda-sqs-worker-cdk` [template](https://github.com/seek-oss/skuba/blob/5ee92123246756a2bc2b055e1bcaa2c7d29653e3/template/lambda-sqs-worker-cdk/cdk.json#L23), the `progress` key was set under `context`

```
{
  "app": "npx ts-node infra/index.ts",
  "context": {
    ...,
    "progress": "events"
  }
}
```

Suggestion:

the `progress` key should be in the upper level:
```
{
  "app": "npx ts-node infra/index.ts",
  "context": {
    ...
  },
  "progress": "events"
}
```

if we update the cdk.json, we can remove the `--progress events` from the [package.json](https://github.com/seek-oss/skuba/blob/5ee92123246756a2bc2b055e1bcaa2c7d29653e3/template/lambda-sqs-worker-cdk/package.json#L18).

Reference: `aws-cdk` [master branch v2.30](https://github.com/aws/aws-cdk/blob/v2.3.0/packages/aws-cdk/README.md#deployment-progress)

Edit: similar [issue](https://github.com/seek-oss/skuba/issues/795) reported

**Comment by 72636c** [comment]
🤦 good pick up. Would you be keen to contribute a patch @bosonseek?

**Comment by bosonseek** [comment]
Hey @72636c , I don't have access to the OSS repo. Can you add me in. Don't wanna fork it :P
