### ISSUE TITLE
preset and tranformIgnorePatterns options for skuba Jest

### ISSUE THREAD

**Issue by pierreloseek** [seek-oss/skuba#878]
Hey team,

A few of our apps are using the command `skuba test` for tests and we have a package with a vulnerability that we want to upgrade but the newest version without the vulnerability uses ES Modules instead of CommonJS. 

At the moment, when running the command `skuba test`, the below error is thrown (both locally and in the build pipeline).

```
Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    ...

    SyntaxError: Cannot use import statement outside a module
```

The workaround for this is to add the two below fields to Jest.mergePreset in our jest.config.ts when importing Jest from skuba. 

```
  transformIgnorePatterns: [`node_modules/(?!(<package_name>)/)`],
  preset: 'ts-jest/presets/js-with-ts',

```

However these two fields are not allowed in https://github.com/seek-oss/skuba/blob/master/src/api/jest/index.ts#L12-L29. I'm just wondering if it would be possible to add `transformIgnorePatterns` and `preset` to that list please?

Thanks!

**Comment by samchungy** [comment]
We are actually just working on this now with the introduction of Typescript 4.7 which adds proper es support.

In the meantime you should be able to spread the Jest preset and override whatever you need for now as a workaround.

eg.
```
export default {
  ... Jest.mergePreset(),
  transformIgnorePatterns: [`node_modules/(?!(<package_name>)/)`],
}
```

**Comment by 72636c** [comment]
You can declare additional options in the generic parameter:

```typescript
Jest.mergePreset<'preset' | 'transformIgnorePatterns'>()
```


https://github.com/seek-oss/skuba/blob/4dc04da5b80cd98112ad5efda309c49c62cc5384/src/api/jest/index.ts?rgh-link-date=2022-05-26T03%3A55%3A16Z#L36-L38

However we wouldn't recommend the above approach. ESM support requires a lot more than hacking the Jest config and will probably require you to modify every source file in your project.

**Comment by pierreloseek** [comment]
Thanks guys! Spreading the Jest preset worked @samchungy!

**Comment by 72636c** [comment]
@pierreloseek if you actually get ESM working without much effort, please do share your magic (maybe internally in `#typescriptification`) 🙂. We're definitely keen on landing proper support when dependent tooling catches up, and TypeScript is now mostly there.

**Comment by pierreloseek** [comment]
@72636c There are a few issues appearing in the build pipeline, but will definitely share if/when I fix them 🙂
